version: "3.7"

services:
  db:
    build:
      context: ../build
      dockerfile: ../build/Dockerfile.postgres
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=ghost171
      - POSTGRES_DB=app
    ports:
      - "3334:3334"
    networks:
      - backend
    volumes: 
      - .database/postgres/data:/var/lib/postgresql/data

  api:
    build:
      context: ../.
      dockerfile: build/Dockerfile
    ports:
      - "4000:4000"
    depends_on: 
      - db
    networks:
      - backend
    volumes:
      - ../.:/go/src/api
    restart: always

networks:
  backend: